services:
  - type: web
    name: hotel-sankara-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m gunicorn --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production

  - type: web
    name: hotel-sankara-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
